service: go-lambda

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeAction
        - lambda:InvokeFunction
      Resource: "*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - sns: hello-dispatcher
  world:
    handler: bin/world

plugins:
  - serverless-sam